import type { Buffer } from 'node:buffer'
import type { Sharp } from 'sharp'
import { randomUUID } from 'node:crypto'
import { access, readFile, rename, rm, stat } from 'node:fs/promises'
import { basename, dirname, join, resolve } from 'node:path'
import { ExifTool } from 'exiftool-vendored'
import sharp from 'sharp'

// The main-process caller owns file authorization and job concurrency.
export const MAX_IMAGE_PIXELS = 100_000_000
export const MAX_IMAGE_SIDE = 32_768
export const SAFE_METADATA_TAGS = [
  'EXIF:Make',
  'EXIF:Model',
  'EXIF:LensMake',
  'EXIF:LensModel',
  'EXIF:DateTimeOriginal',
  'EXIF:OffsetTimeOriginal',
  'EXIF:SubSecTimeOriginal',
  'EXIF:ExposureTime',
  'EXIF:FNumber',
  'EXIF:ISO',
  'EXIF:FocalLength',
  'EXIF:FocalLengthIn35mmFormat',
  'EXIF:ExposureCompensation',
  'EXIF:Artist',
  'EXIF:Copyright',
  'EXIF:ImageDescription',
  'EXIF:GPSLatitude',
  'EXIF:GPSLatitudeRef',
  'EXIF:GPSLongitude',
  'EXIF:GPSLongitudeRef',
  'EXIF:GPSAltitude',
  'EXIF:GPSAltitudeRef',
] as const

export interface ExportOptions {
  format: 'jpeg' | 'png' | 'tiff'
  bitDepth: 8 | 16
  profile: 'srgb' | 'p3' | { path: string }
  quality?: number
  dpi?: number
  metadataSource?: string
}

export function validateDimensions(width: number, height: number): void {
  if (
    ![width, height].every(
      n => Number.isInteger(n) && n > 0 && n <= MAX_IMAGE_SIDE,
    )
    || width * height > MAX_IMAGE_PIXELS
  ) {
    throw new Error('Image dimensions exceed the render budget')
  }
}

/** Decodes the first page and bakes in all eight EXIF orientations. */
export function openImage(input: string | Buffer): Sharp {
  return sharp(input, {
    limitInputPixels: MAX_IMAGE_PIXELS,
    failOn: 'error',
    pages: 1,
  })
    .autoOrient()
    .pipelineColourspace('rgb16')
}

/** Native resize primitive; the caller supplies geometry computed by the layout layer. */
export function resizeImage(
  input: string | Buffer,
  width: number,
  height: number,
): Sharp {
  validateDimensions(width, height)
  return openImage(input).resize(width, height, { fit: 'cover' })
}

/** Pango/FreeType renders plain text with an explicitly supplied local font. */
export async function renderText(
  text: string,
  fontFile: string,
  font: string,
  width: number,
): Promise<Buffer> {
  validateDimensions(width, 1)
  if (text.length > 4096)
    throw new Error('Text exceeds the render budget')
  await access(fontFile)
  const escaped = text.replace(
    /[&<>"']/g,
    ch =>
      ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        '\'': '&apos;',
      })[ch]!,
  )
  return sharp({
    text: { text: escaped, fontfile: fontFile, font, width, rgba: true },
    limitInputPixels: MAX_IMAGE_PIXELS,
  })
    .png()
    .toBuffer()
}

/** One bounded ExifTool worker per adapter. Close it during application shutdown. */
export class ImageMetadata {
  private readonly tool = new ExifTool({
    maxProcs: 1,
    taskTimeoutMillis: 15_000,
  })

  async inspect(path: string) {
    const metadata = await sharp(path, {
      limitInputPixels: MAX_IMAGE_PIXELS,
      failOn: 'error',
      pages: 1,
    }).metadata()
    validateDimensions(metadata.width, metadata.height)
    const tags = await this.tool.readRaw(path, {
      readArgs: ['-n', ...SAFE_METADATA_TAGS.map(tag => `-${tag}`)],
    })
    return {
      width: metadata.autoOrient.width,
      height: metadata.autoOrient.height,
      orientation: metadata.orientation ?? 1,
      depth: metadata.depth,
      hasProfile: metadata.hasProfile,
      tags,
    }
  }

  async copySafeTags(source: string, destination: string): Promise<void> {
    // Never copy directories wholesale: source dimensions, sample depth, ICC and thumbnails
    // must not replace properties generated by the output encoder.
    await access(source)
    const tags = await this.tool.readRaw(source, {
      readArgs: ['-n', ...SAFE_METADATA_TAGS.map(tag => `-${tag}`)],
    })
    if (
      !SAFE_METADATA_TAGS.some(tag => Object.hasOwn(tags, tag.split(':')[1]!))
    )
      return
    const result = await this.tool.write(
      destination,
      {},
      {
        writeArgs: [
          '-overwrite_original',
          '-TagsFromFile',
          resolve(source),
          ...SAFE_METADATA_TAGS.map(tag => `-${tag}`),
        ],
      },
    )
    if (result.warnings?.length) {
      throw new Error(
        `Metadata transfer failed: ${result.warnings.join('; ')}`,
      )
    }
  }

  async close(): Promise<void> {
    await this.tool.end()
  }
}

/** Writes atomically after encoding and optional metadata copy both succeed. */
export async function exportImage(
  pipeline: Sharp,
  destination: string,
  options: ExportOptions,
  metadata?: ImageMetadata,
): Promise<void> {
  const { format, bitDepth, quality = 92, dpi = 72 } = options
  if (!['jpeg', 'png', 'tiff'].includes(format) || ![8, 16].includes(bitDepth))
    throw new Error('Unsupported export format or depth')
  if (!Number.isInteger(quality) || quality < 1 || quality > 100)
    throw new Error('Invalid JPEG quality')
  if (!Number.isFinite(dpi) || dpi < 1)
    throw new Error('Invalid DPI')
  if (options.metadataSource && !metadata)
    throw new Error('Metadata adapter is required')
  const profile
    = typeof options.profile === 'string'
      ? options.profile
      : options.profile.path
  let expectedProfile: Buffer | undefined
  if (typeof options.profile !== 'string') {
    const file = await stat(profile)
    if (file.size < 128 || file.size > 16 * 1024 * 1024)
      throw new Error('Invalid ICC profile size')
    expectedProfile = await readFile(profile)
    if (expectedProfile.toString('ascii', 36, 40) !== 'acsp')
      throw new Error('Invalid ICC profile header')
  }
  const depth = format === 'jpeg' ? 8 : bitDepth
  let output = pipeline
    .clone()
    .pipelineColourspace('rgb16')
    .withIccProfile(profile)
    .toColourspace(depth === 16 ? 'rgb16' : 'srgb')
    .withExif({ IFD0: { Orientation: '1' } })
    .withDensity(dpi)
  if (format === 'jpeg') {
    output = output
      .flatten({ background: '#ffffff' })
      .jpeg({ quality, chromaSubsampling: '4:4:4' })
  }
  else if (format === 'png') {
    output = output.png()
  }
  else {
    output = output.tiff({ compression: 'lzw', predictor: 'horizontal' })
  }
  const temp = join(
    dirname(destination),
    `.${basename(destination)}.${randomUUID()}.${format}`,
  )
  const warnings: string[] = []
  output.on('warning', warning => warnings.push(String(warning)))
  try {
    const info = await output.toFile(temp)
    if (warnings.length)
      throw new Error(`Image encoding failed: ${warnings.join('; ')}`)
    validateDimensions(info.width, info.height)
    const encoded = await sharp(temp).metadata()
    if (expectedProfile && !encoded.icc?.equals(expectedProfile)) {
      throw new Error(
        'Output ICC profile does not match the requested profile',
      )
    }
    if (!encoded.icc?.length)
      throw new Error('Output ICC profile is missing or invalid')
    if (options.metadataSource)
      await metadata!.copySafeTags(options.metadataSource, temp)
    await rename(temp, destination)
  }
  finally {
    await rm(temp, { force: true })
  }
}
